"""
Project Euler Problem 2
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

fib = [0, 1]

def main():
	i = 2
	nextfib = 1
	s = 0
	while nextfib <= 4*10**6:
		if nextfib%2 == 0:
			s += nextfib
		fib.append(nextfib)
		i += 1
		nextfib = fib[i-1] + fib[i-2]
	print(s)
main()
